#!/usr/bin/env bash
set -e # halt script on error

# Pipe 'yes' into pebble tool to accept terms and conditions
yes | ./pebble-dev/pebble-sdk-$PEBBLE_TOOL-linux64/bin/pebble build

# Run the C linter
source ./pebble-dev/pebble-sdk-$PEBBLE_TOOL-linux64/.env/bin/activate
cpplint src/*
deactivate

if [[ $TRAVIS_BRANCH == 'master' ]]; then
  ./pebble-dev/pebble-sdk-$PEBBLE_TOOL-linux64/bin/pebble release publish
fi
