#!/usr/bin/env bash
set -e # halt script on error

mkdir pebble-dev
cd pebble-dev
curl -O https://s3.amazonaws.com/assets.getpebble.com/pebble-tool/pebble-sdk-$PEBBLE_TOOL-linux64.tar.bz2
tar -jxf pebble-sdk-$PEBBLE_TOOL-linux64.tar.bz2

cd pebble-sdk-$PEBBLE_TOOL-linux64
virtualenv --no-site-packages .env
source .env/bin/activate
pip install -r requirements.txt
deactivate
